### ISSUE TITLE
Add Typescript typing

### ISSUE THREAD

**Issue by robertkiel** [libp2p/js-peer-info#87]
I've created some incomplete typings for `peer-info` here:

https://github.com/hoprnet/hopr-types/blob/557f90622ac351b3e43ed4cb2b9ac9ff16930cc4/types/peer-info.d.ts

You might use them as a template file ;-)

**Comment by vasco-santos** [comment]
Hey @robertkiel 

Thanks for sharing this, but we just got a PR with them merged on [libp2p/js-peer-info#86](https://github.com/libp2p/js-peer-info/pull/86)

**Comment by robertkiel** [comment]
Alright. That's also fine. Could you also export the types in the package.json file?

```
"types": "src/index.d.ts"
```
